export const table_data =[{rank:1,brandName:"Abilify"},
{rank:2,brandName:"Humira"},
{rank:3,brandName:"Nexium"},
{rank:4,brandName:"Crestor"},
{rank:5,brandName:"Enbrel"},
{rank:6,brandName:"Advair Diskus"},
{rank:8,brandName:"Remicade"},
{rank:9,brandName:"Lantus Solostar"},
{rank:10,brandName:"Neulasta"},
{rank:11,brandName:"Copaxone"},
{rank:12,brandName:"Rituxan"},
{rank:13,brandName:"Spiriva"},
{rank:14,brandName:"Januvia"},
{rank:15,brandName:"Lantus"},
{rank:16,brandName:"Atripla"},
{rank:17,brandName:"Cymbalta"},
{rank:18,brandName:"Avastin"},
{rank:19,brandName:"Lyrica"},
{rank:20,brandName:"OxyContin"},
{rank:21,brandName:"Celebrex"},
{rank:22,brandName:"Epogen"},
{rank:23,brandName:"Truvada"},
{rank:24,brandName:"Diovan"},
{rank:25,brandName:"Levemir"},
{rank:26,brandName:"Gleevec"},
{rank:27,brandName:"Herceptin"},
{rank:28,brandName:"Vyvanse"},
{rank:29,brandName:"Lucentis"},
{rank:30,brandName:"Zetia"},
{rank:31,brandName:"Combivent"},
{rank:32,brandName:"Symbicort"},
{rank:33,brandName:"Namenda"},
{rank:33,brandName:"Incivo"},
{rank:34,brandName:"NovoLog FlexPen"},
{rank:35,brandName:"Xarelto"},
{rank:35,brandName:"AndroGel"},
{rank:36,brandName:"NovoLog"},
{rank:37,brandName:"Humalog"},
{rank:37,brandName:"Enoxaparin"},
{rank:38,brandName:"Suboxone"},
{rank:38,brandName:"Ritalin"},
{rank:40,brandName:"Viagra"},
{rank:41,brandName:"Seroquel XR"},
{rank:41,brandName:"ProAir HFA"},
{rank:43,brandName:"Alimta"},
{rank:44,brandName:"Victoza"},
{rank:47,brandName:"Synagis"},
{rank:48,brandName:"Avonex"},
{rank:49,brandName:"Renvela"},
{rank:50,brandName:"Rebif"},
{rank:51,brandName:"Cialis"},
{rank:52,brandName:"Gilenya"},
{rank:53,brandName:"Nasonex"},
{rank:54,brandName:"Stelara"}]